"use client";
import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { ApiError } from "@/lib/errors";
import { api, seg } from "@/lib/client/api";
import { scope, downloadJson, type HookEvent, type Hook, type PageResult } from "@/lib/hook/api";
import { formatDateTime } from "@/lib/format";
import { useHookScope } from "./context";
import { Blank, Modal, Pager, Status } from "./common";
import { Page, PageHeader, Surface } from "@/components/foundation/layout/layout";
import { ErrorAlert } from "@/components/foundation/feedback/error-alert";
import { Button } from "@/components/silicon-ui/button/button";
import { Select } from "@/components/silicon-ui/select/select";
import { Checkbox } from "@/components/silicon-ui/checkbox/checkbox";
import { Input } from "@/components/silicon-ui/input/input";

export function EventTable({ events, select }: { events: HookEvent[]; select: (event: HookEvent) => void }) {
  return <><div className="hook-table-wrap hook-event-table"><table className="hook-table"><thead><tr><th scope="col">Request</th><th scope="col">Received</th><th scope="col">Silicon</th><th scope="col">Result</th><th scope="col"><span className="sr-only">Details</span></th></tr></thead><tbody>{events.map(event => <tr key={event.id}><td><strong>{event.provider}</strong><span className="hook-event-summary">{event.summary || event.request.path}</span></td><td>{formatDateTime(event.received_at)}</td><td>{event.silicon.id || event.silicon.uuid}</td><td><Status value={event.reason_code || "verified"} /></td><td><Button variant="ghost" size="sm" onClick={() => select(event)}>Inspect</Button></td></tr>)}</tbody></table></div><div className="hook-event-cards">{events.map(event => <Surface key={event.id} className="hook-stack"><div className="hook-toolbar"><strong>{event.provider}</strong><Status value={event.reason_code || "verified"} /></div><p className="hook-muted">{formatDateTime(event.received_at)} · {event.silicon.id || event.silicon.uuid}</p><p>{event.summary || event.request.path}</p><Button variant="secondary" size="sm" onClick={() => select(event)}>Inspect</Button></Surface>)}</div></>;
}
export function EventInspector({ event, close }: { event: HookEvent; close: () => void }) {
  const [view, setView] = useState("request");
  return <Modal title={event.reason_code ? "Blocked request" : "Verified request"} description={`${event.provider} · ${formatDateTime(event.received_at)}`} close={close}><div className="hook-stack"><Select label="Inspect" value={view} onValueChange={setView} options={[{ value: "request", label: "Request body" }, { value: "headers", label: "Ordered headers" }, { value: "json", label: "Full event JSON" }]} />{event.reason_code && <div className="hook-notice"><strong>{event.reason_code}</strong><p>{event.reason_detail}</p></div>}<dl className="hook-facts"><dt>Method</dt><dd>{event.request.method}</dd><dt>URL</dt><dd>{event.request.url}</dd><dt>Content type</dt><dd>{event.request.content_type || "Not provided"}</dd><dt>Remote IP</dt><dd>{event.request.remote_ip}</dd><dt>Event ID</dt><dd>{event.id}</dd></dl>{view === "headers" ? <div className="hook-table-wrap"><table className="hook-table"><thead><tr><th>Header</th><th>Value</th></tr></thead><tbody>{event.request.headers.map(([key, value], index) => <tr key={index}><td>{key}</td><td>{value}</td></tr>)}</tbody></table></div> : view === "json" ? <pre>{JSON.stringify(event, null, 2)}</pre> : <><p className="hook-muted">{event.request.body_base64 ? "Binary body encoded as base64" : "UTF-8 request body"}</p><pre>{event.request.body ?? event.request.body_base64 ?? "Empty body"}</pre></>}<Button variant="secondary" onClick={() => downloadJson(event, `hook-event-${event.id}.json`)}>Download full JSON</Button></div></Modal>;
}
export function HistoryPage({ blocked = false, delivery = false }: { blocked?: boolean; delivery?: boolean }) {
  const { selected } = useHookScope();
  return <Page><PageHeader title={delivery ? "Deliveries" : blocked ? "Blocked requests" : "History"} description={delivery ? "Follow each event from publication to destination receipt." : blocked ? "See why a request was rejected, with its original body and headers." : "Every verified request, retained for 14 days."} />{selected ? <History key={`${selected.silicon.uuid}-${blocked}-${delivery}`} uuid={selected.silicon.uuid} blocked={blocked} delivery={delivery} /> : <Blank title="Choose a Silicon">Select a Silicon to inspect its requests.</Blank>}</Page>;
}
function History({ uuid, blocked, delivery }: { uuid: string; blocked: boolean; delivery: boolean }) {
  const [cursors, setCursors] = useState<string[]>([]);
  const [hook, setHook] = useState("all");
  const [limit, setLimit] = useState("50");
  const [provider, setProvider] = useState("");
  const [inspect, setInspect] = useState<HookEvent | null>(null);
  const [publication, setPublication] = useState<HookEvent | null>(null);
  const hooks = useQuery({ queryKey: ["hooks", uuid], queryFn: () => api.get<PageResult<Hook>>(scope(uuid, "/hooks"), { query: { include_deleted: true } }) });
  const query = useQuery({ queryKey: ["events", uuid, blocked, hook, limit, cursors.at(-1)], queryFn: () => api.get<PageResult<HookEvent>>(scope(uuid, blocked ? "/blocked-requests" : "/events"), { query: { hook_id: hook === "all" ? undefined : hook, limit, cursor: cursors.at(-1) } }) });
  const events = (query.data?.items ?? []).filter(event => event.provider.toLowerCase().includes(provider.toLowerCase()));
  return <div className="hook-stack">{delivery && <DeliveryPreferences uuid={uuid} />}<div className="hook-filters"><Select label="Hook" value={hook} onValueChange={value => { setHook(value); setCursors([]); }} options={[{ value: "all", label: "All hooks" }, ...(hooks.data?.items ?? []).map(h => ({ value: h.id, label: h.name }))]} /><Select label="Requests per page" value={limit} onValueChange={value => { setLimit(value); setCursors([]); }} options={[25, 50, 100, 500, 1000, 10000].map(value => ({ value: String(value), label: String(value) }))} /></div><div className="hook-toolbar"><Input label="Filter provider on this page" value={provider} onChange={e => setProvider(e.target.value)} /><div className="hook-actions"><Button variant="secondary" onClick={() => downloadJson(events, blocked ? "blocked-requests.json" : "verified-events.json")} disabled={!events.length}>Export page</Button><Button variant="secondary" onClick={() => void query.refetch()} loading={query.isFetching}>Refresh</Button></div></div>{query.error && <ErrorAlert error={query.error} />}{query.isLoading ? <p role="status">Loading requests…</p> : events.length ? <EventTable events={events} select={delivery ? setPublication : setInspect} /> : <Blank title={provider ? "No requests from this provider on this page" : "No requests yet"}>{blocked ? "Requests that fail signature verification appear here." : "Verified provider requests appear here as they arrive."}</Blank>}<Pager count={events.length} previous={cursors.length > 0} next={query.data?.next_cursor} onPrevious={() => setCursors(old => old.slice(0, -1))} onNext={() => { if (query.data?.next_cursor) setCursors(old => [...old, query.data!.next_cursor!]); }} />{inspect && <EventInspector event={inspect} close={() => setInspect(null)} />}{publication && <Publication event={publication} close={() => setPublication(null)} inspect={() => { setInspect(publication); setPublication(null); }} />}</div>;
}
type PublicationResult = { event_id: string; state: string; detail?: string; recipient?: string; delivery?: string; silent?: boolean | null; attempts?: number; accepted_at?: string | null; next_attempt_at?: string; expires_at?: string; last_error_code?: string | null; recipient_status_error?: string | null; recipient_receipt?: { deliveries: { webhook_id: string; delivery_acked: boolean; read_acked: boolean }[]; read: boolean; more_destinations: boolean } | null };
function Publication({ event, close, inspect }: { event: HookEvent; close: () => void; inspect: () => void }) {
  const query = useQuery({ queryKey: ["publication", event.id], queryFn: () => api.get<PublicationResult>(scope(event.silicon.uuid, `/events/${seg(event.id)}/publication`)), refetchInterval: 10000 });
  const data = query.data;
  return <Modal title="Event delivery" description={`${event.provider} · ${formatDateTime(event.received_at)}`} close={close}><div className="hook-stack"><p className="hook-notice">Receipt confirms durable delivery storage. Acceptance confirms the destination accepted the event. Neither confirms completed work.</p>{query.error && <ErrorAlert error={query.error} />}{query.isLoading && <p role="status">Checking delivery…</p>}{data && <><Status value={data.state} />{data.detail && <p>{data.detail}</p>}{data.recipient && <dl className="hook-facts"><dt>Recipient</dt><dd>{data.recipient}</dd><dt>Delivery policy</dt><dd>{data.delivery === "required" ? "Automation" : "Notification"}</dd><dt>Notifications</dt><dd>{data.silent == null ? "Not confirmed" : data.silent ? "Muted" : "Visible"}</dd><dt>Send attempts</dt><dd>{data.attempts}</dd><dt>Accepted</dt><dd>{formatDateTime(data.accepted_at)}</dd><dt>Next attempt</dt><dd>{formatDateTime(data.next_attempt_at)}</dd><dt>Retained until</dt><dd>{formatDateTime(data.expires_at)}</dd></dl>}{data.last_error_code && <p className="hook-notice">{data.last_error_code.replaceAll("_", " ")}{data.last_error_code === "required_delivery_not_enabled" ? ": Enable webhook automation in the recipient app. Hook will retry automatically." : ""}</p>}{data.recipient_status_error && <p>Destination status is temporarily unavailable. The send status above remains valid.</p>}{data.recipient_receipt && <><h3>Destination receipts</h3>{data.recipient_receipt.deliveries.map(receipt => <Surface key={receipt.webhook_id}><strong>{receipt.webhook_id}</strong><p>Received: {receipt.delivery_acked ? "Confirmed" : "Not confirmed"} · Accepted: {receipt.read_acked ? "Confirmed" : "Not confirmed"}</p></Surface>)}{data.recipient_receipt.more_destinations && <p>More destinations exist than this response includes.</p>}</>}</>}<div className="hook-actions"><Button variant="secondary" onClick={() => void query.refetch()}>Refresh status</Button><Button onClick={inspect}>Inspect request</Button></div></div></Modal>;
}
function DeliveryPreferences({ uuid }: { uuid: string }) {
  const [error, setError] = useState<ApiError | null>(null);
  const [busy, setBusy] = useState(false);
  const status = useQuery({ queryKey: ["delivery"], queryFn: () => api.get<{ enabled: boolean; reason?: string }>("/api/v3/delivery") });
  const subscription = useQuery({ queryKey: ["subscription", uuid], queryFn: () => api.get<{ receiving: boolean; subscription: unknown }>(scope(uuid, "/delivery/subscription")) });
  async function subscribe() { setBusy(true); setError(null); try { if (subscription.data?.subscription) await api.delete(scope(uuid, "/delivery/subscription")); else { await api.post("/api/v3/delivery/recipient"); await api.post(scope(uuid, "/delivery/subscription")); } await subscription.refetch(); } catch (cause) { setError(cause instanceof ApiError ? cause : new ApiError({status: 0, message: String(cause), code: "network_error"})); } finally { setBusy(false); } }
  return <Surface className="hook-stack"><div className="hook-toolbar"><div><h2 className="hook-panel-title">Your event copies</h2><p className="hook-muted">Receive future events in your notification destination. Earlier events are not backfilled.</p></div><Button variant="secondary" loading={busy} disabled={(!status.data?.enabled && !subscription.data?.subscription) || subscription.isLoading} onClick={() => void subscribe()}>{subscription.data?.subscription ? "Stop receiving copies" : "Receive event copies"}</Button></div>{status.data?.enabled === false && <p className="hook-notice">Delivery is off: {status.data.reason}. Requests remain available in history.</p>}{subscription.data?.receiving && <p role="status">Receiving future events from this Silicon.</p>}{[status.error, subscription.error, error].filter(Boolean).map((item, i) => <ErrorAlert key={i} error={item!} />)}</Surface>;
}
export function LivePage() {
  const { items, selected } = useHookScope();
  const [uuids, setUuids] = useState<string[]>([]);
  const [running, setRunning] = useState(false);
  const [auto, setAuto] = useState(true);
  const [events, setEvents] = useState<HookEvent[]>([]);
  const [inspect, setInspect] = useState<HookEvent | null>(null);
  const chosen = uuids.length ? uuids : selected ? [selected.silicon.uuid] : [];
  const query = useQuery({ queryKey: ["live", ...chosen], enabled: running && !!chosen.length, queryFn: async ({ signal }) => {
    const pages = await Promise.all(chosen.map(uuid => api.get<PageResult<HookEvent>>(scope(uuid, "/events"), { query: { limit: 32 }, signal })));
    const fresh = pages.flatMap(page => page.items);
    setEvents(previous => [...new Map([...previous, ...fresh].map(event => [event.id, event])).values()].sort((a, b) => b.received_at.localeCompare(a.received_at) || (b.delivery_sequence ?? 0) - (a.delivery_sequence ?? 0)).slice(0, 32));
    return true;
  }, retry: auto ? 3 : false, retryDelay: attempt => Math.min(30000, 1000 * 2 ** attempt), refetchInterval: query => !auto && query.state.error ? false : query.state.error ? 30000 : 2500, refetchIntervalInBackground: false });
  return <Page><PageHeader title="Live stream" description="Watch the latest verified requests while this page is open." actions={<Status value={!running ? "disconnected" : query.error ? "reconnecting" : query.isFetching && !query.data ? "connecting" : "connected"} />} /><div className="hook-stack"><Surface className="hook-stack"><div className="hook-live-pick">{items.map(item => <Checkbox key={item.silicon.uuid} label={item.silicon.id || item.silicon.uuid} disabled={running} checked={chosen.includes(item.silicon.uuid)} onCheckedChange={on => setUuids(on === true ? [...new Set([...chosen, item.silicon.uuid])] : chosen.filter(uuid => uuid !== item.silicon.uuid))} />)}</div><div className="hook-toolbar"><Button disabled={!chosen.length} onClick={() => { if (!running) setEvents([]); setRunning(!running); }}>{running ? "Disconnect" : "Connect"}</Button><Checkbox label="Reconnect automatically" checked={auto} onCheckedChange={on => setAuto(on === true)} /></div></Surface><p className="hook-notice">This view refreshes every few seconds and keeps the most recent 32 events. It never acknowledges or completes work. Use History for all retained requests.</p>{query.error && <ErrorAlert error={query.error} action={<Button variant="secondary" onClick={() => void query.refetch()}>Retry now</Button>} />}{events.length ? <EventTable events={events} select={setInspect} /> : <Blank title={running ? "Listening for requests" : "Ready when you are"}>{running ? "Verified requests appear as providers send them." : "Choose Silicons and connect to watch their requests."}</Blank>}{inspect && <EventInspector event={inspect} close={() => setInspect(null)} />}</div></Page>;
}
