// Generated by ../build.py; credentials are supplied by the runtime.
const SPEC={
  "slug": "clients",
  "name": "Hook Web & CLI",
  "subtitle": "Browser pages, command outcomes and client versions",
  "queries": {
    "totals": "SELECT toInt32(countIf(source='web' AND event='page_view')) AS views,toInt32(countIf(source='cli' AND event='command' AND outcome IN ('succeeded','failed'))) AS commands,toInt32(countIf(source IN ('cli','daemon','client') AND outcome='failed')) AS failures,toInt32(countIf(source='web' AND event='error')) AS errors FROM (SELECT record.event.event_id::String AS event_id, any(record.recorded_at_ms::Float64) AS at_ms, any(record.event.source::String) AS source, any(record.event.step::String) AS event, any(record.event.outcome::String) AS outcome, any(record.event.operation::String) AS operation, any(record.event.route::String) AS route, any(record.event.method::String) AS method, any(record.event.status::Nullable(Int32)) AS status, any(record.event.duration_ms::Nullable(Float64)) AS latency_ms, any(record.event.progress::Nullable(Int32)) AS progress, any(record.event.version::String) AS version, any(record.event.trace_id::String) AS request_id, greatest(0., toFloat64(min(registered_ts_ms)) - at_ms) AS lag_ms FROM siliconhook WHERE record.service::String = 'silicon-hook' AND record.environment_id::String = '00000000-0000-0000-0000-000000000000' AND record.recorded_at_ms::Float64 >= toUnixTimestamp64Milli(now64()) - 86400000 AND record.event.event_id::String != '' AND record.event.step::String != 'verification' GROUP BY event_id) ",
    "pages": "SELECT operation,toInt32(count()) AS views,toFloat64(max(at_ms)) AS last_seen_ms FROM (SELECT record.event.event_id::String AS event_id, any(record.recorded_at_ms::Float64) AS at_ms, any(record.event.source::String) AS source, any(record.event.step::String) AS event, any(record.event.outcome::String) AS outcome, any(record.event.operation::String) AS operation, any(record.event.route::String) AS route, any(record.event.method::String) AS method, any(record.event.status::Nullable(Int32)) AS status, any(record.event.duration_ms::Nullable(Float64)) AS latency_ms, any(record.event.progress::Nullable(Int32)) AS progress, any(record.event.version::String) AS version, any(record.event.trace_id::String) AS request_id, greatest(0., toFloat64(min(registered_ts_ms)) - at_ms) AS lag_ms FROM siliconhook WHERE record.service::String = 'silicon-hook' AND record.environment_id::String = '00000000-0000-0000-0000-000000000000' AND record.recorded_at_ms::Float64 >= toUnixTimestamp64Milli(now64()) - 86400000 AND record.event.event_id::String != '' AND record.event.step::String != 'verification' GROUP BY event_id) WHERE source='web' AND event='page_view' GROUP BY operation ORDER BY views DESC LIMIT 20",
    "activity": "SELECT source,event,operation,outcome,version,toInt32(count()) AS events,toFloat64(max(at_ms)) AS last_seen_ms FROM (SELECT record.event.event_id::String AS event_id, any(record.recorded_at_ms::Float64) AS at_ms, any(record.event.source::String) AS source, any(record.event.step::String) AS event, any(record.event.outcome::String) AS outcome, any(record.event.operation::String) AS operation, any(record.event.route::String) AS route, any(record.event.method::String) AS method, any(record.event.status::Nullable(Int32)) AS status, any(record.event.duration_ms::Nullable(Float64)) AS latency_ms, any(record.event.progress::Nullable(Int32)) AS progress, any(record.event.version::String) AS version, any(record.event.trace_id::String) AS request_id, greatest(0., toFloat64(min(registered_ts_ms)) - at_ms) AS lag_ms FROM siliconhook WHERE record.service::String = 'silicon-hook' AND record.environment_id::String = '00000000-0000-0000-0000-000000000000' AND record.recorded_at_ms::Float64 >= toUnixTimestamp64Milli(now64()) - 86400000 AND record.event.event_id::String != '' AND record.event.step::String != 'verification' GROUP BY event_id) WHERE source IN ('web','cli','daemon','client') GROUP BY source,event,operation,outcome,version ORDER BY events DESC LIMIT 60"
  },
  "cards": [
    {
      "label": "Page views",
      "key": "views",
      "detail": "Browser-reported views, not unique visitors",
      "tone": "neutral",
      "unit": "",
      "group": "totals"
    },
    {
      "label": "CLI commands",
      "key": "commands",
      "detail": "Succeeded and failed completions",
      "tone": "neutral",
      "unit": "",
      "group": "totals"
    },
    {
      "label": "Native failures",
      "key": "failures",
      "detail": "CLI, daemon and client signals",
      "tone": "danger",
      "unit": "",
      "group": "totals"
    },
    {
      "label": "Browser errors",
      "key": "errors",
      "detail": "Reported error events",
      "tone": "danger",
      "unit": "",
      "group": "totals"
    }
  ],
  "tables": [
    {
      "rows_key": "pages",
      "id": "pages",
      "title": "Browser pages",
      "note": "Only allowlisted page names are collected.",
      "columns": [
        {
          "key": "operation",
          "label": "Page",
          "kind": "text"
        },
        {
          "key": "views",
          "label": "Views",
          "kind": "number"
        },
        {
          "key": "last_seen_ms",
          "label": "Last seen",
          "kind": "time"
        }
      ]
    },
    {
      "rows_key": "activity",
      "id": "activity",
      "title": "Client activity",
      "note": "Top 60 source, step, operation, outcome and version groups. No command arguments are collected.",
      "columns": [
        {
          "key": "source",
          "label": "Source",
          "kind": "text"
        },
        {
          "key": "event",
          "label": "Step",
          "kind": "text"
        },
        {
          "key": "operation",
          "label": "Operation",
          "kind": "text"
        },
        {
          "key": "outcome",
          "label": "Outcome",
          "kind": "text"
        },
        {
          "key": "version",
          "label": "Version",
          "kind": "text"
        },
        {
          "key": "events",
          "label": "Events",
          "kind": "number"
        },
        {
          "key": "last_seen_ms",
          "label": "Last seen",
          "kind": "time"
        }
      ]
    }
  ]
};
const TRACE_SQL="SELECT at_ms,source,event,outcome,operation,route,status,latency_ms,request_id FROM (SELECT record.event.event_id::String AS event_id, any(record.recorded_at_ms::Float64) AS at_ms, any(record.event.source::String) AS source, any(record.event.step::String) AS event, any(record.event.outcome::String) AS outcome, any(record.event.operation::String) AS operation, any(record.event.route::String) AS route, any(record.event.method::String) AS method, any(record.event.status::Nullable(Int32)) AS status, any(record.event.duration_ms::Nullable(Float64)) AS latency_ms, any(record.event.progress::Nullable(Int32)) AS progress, any(record.event.version::String) AS version, any(record.event.trace_id::String) AS request_id, greatest(0., toFloat64(min(registered_ts_ms)) - at_ms) AS lag_ms FROM siliconhook WHERE record.service::String = 'silicon-hook' AND record.environment_id::String = '00000000-0000-0000-0000-000000000000' AND record.recorded_at_ms::Float64 >= toUnixTimestamp64Milli(now64()) - 86400000 AND record.event.event_id::String != '' AND record.event.step::String != 'verification' GROUP BY event_id)";

function present(raw){
 const data={title:SPEC.name,subtitle:SPEC.subtitle,scope:'Production · last 24 hours · deduplicated event IDs · verification probes excluded',generated_at:new Date().toISOString(),trace_enabled:true,raw,tables:SPEC.tables,cards:SPEC.cards.map(c=>({...c,value:raw[c.group]?.[0]?.[c.key]??null}))};
 if(SPEC.slug==='overview'){
  data.services=['backend','worker','web','daemon'].map(source=>({source,...(raw.sources?.find(r=>r.source===source)||{last_seen_ms:null})}));
  const start=Math.floor((Date.now()-86400000)/3600000)*3600000;
  const byHour=new Map((raw.trend||[]).map(r=>[Number(r.at_ms),Number(r.value)]));
  data.chart={title:'Event volume',note:'Hourly buckets · UTC · first and current hours are partial',points:Array.from({length:25},(_,i)=>({at_ms:start+i*3600000,value:byHour.get(start+i*3600000)||0}))};
 }
 const bytes=v=>{let n=0;for(const c of JSON.stringify(v)){const p=c.codePointAt(0);n+=p<128?1:p<2048?2:p<65536?3:4;}return n;};
 while(bytes(data)>60000){const largest=Object.values(raw).filter(r=>Array.isArray(r)&&r.length>5).sort((a,b)=>JSON.stringify(b).length-JSON.stringify(a).length)[0];if(!largest)throw new Error('Window state exceeds limit');largest.pop();data.rows_trimmed=true;}
 return data;
}
export default defineProcessor({
 init:async()=>{const raw={};for(const [key,sql] of Object.entries(SPEC.queries))raw[key]=await mission_control.query(sql);return present(raw);},
 subscriptions:Object.fromEntries(Object.entries(SPEC.queries).map(([key,sql])=>[key,{triggers:[{table:'siliconhook'}],sql,mode:'snapshot',onTrigger:(json,rows)=>present({...json.raw,[key]:rows})}])),
 tools:{summary:{args:{},run:json=>({title:json.title,scope:json.scope,generated_at:json.generated_at,cards:json.cards})},trace_request:{args:{request_id:'string'},run:async(json,{request_id})=>{if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(request_id))throw new Error('Enter a valid trace UUID');return {request_id,rows:await mission_control.query(TRACE_SQL+" WHERE request_id='"+request_id.toLowerCase()+"' ORDER BY at_ms ASC LIMIT 40")};}}}
});
