import { createHmac, randomUUID } from "node:crypto";
import { mkdirSync, readFileSync } from "node:fs";
import { expect, test } from "@playwright/test";
import { accountsSession, runAccounts, signIn, watchErrors, sameOrigin, BASE } from "./support";

test("a custodian manages hooks, inspects real signed and blocked deliveries, and shares with a Carbon", async ({ browser }) => {
  const context = await accountsSession(browser, "carbon");
  const page = await context.newPage();
  const errors = watchErrors(page);
  await signIn(page, runAccounts().carbon.email);
  const silicon = JSON.parse(readFileSync("test-results/.auth/silicon.json", "utf8"));
  await expect(page.getByRole("button", {name: "New hook", exact: true})).toBeVisible();
  await page.getByRole("button", {name: "New hook", exact: true}).click();
  const editor = page.getByRole("dialog", {name: "Create a hook"});
  await editor.getByRole("textbox", {name: "Name", exact: true}).fill("Release events");
  await editor.getByRole("textbox", {name: "Description", exact: true}).fill("Deployment updates for this Silicon");
  await editor.getByRole("button", {name: "Create hook", exact: true}).click();
  const reveal = page.getByRole("dialog", {name: "Save your signing secret"});
  await expect(reveal).toBeVisible();
  const codes = await reveal.locator("code").allTextContents();
  const endpoint = codes[0]!;
  const secret = codes[1]!;
  expect(secret).toMatch(/^v1\./);
  await reveal.getByRole("button", {name: "Done", exact: true}).click();
  const card = page.locator(".hook-card").filter({hasText: "Release events"});
  await expect(card).toContainText("HMAC-SHA256");
  const raw = JSON.stringify({action: "released", version: "test"});
  const messageId = randomUUID(); const timestamp = String(Math.floor(Date.now() / 1000));
  const signature = createHmac("sha256", secret).update(`${messageId}.${timestamp}.${raw}`).digest("base64");
  const accepted = await context.request.post(endpoint, {data: raw, headers: {"Content-Type": "application/json", "webhook-id": messageId, "webhook-timestamp": timestamp, "webhook-signature": `v1,${signature}`}});
  expect(accepted.status()).toBe(200);
  const blocked = await context.request.post(endpoint, {data: {action: "unsigned"}});
  expect(blocked.status()).toBe(200);
  await page.goto("/history");
  await expect(page.getByRole("button", {name: "Inspect", exact: true})).toBeVisible();
  await page.getByRole("button", {name: "Inspect", exact: true}).click();
  const inspector = page.getByRole("dialog", {name: "Verified request"});
  await expect(inspector).toContainText(raw);
  await page.keyboard.press("Escape");
  await page.goto("/blocked");
  await page.getByRole("button", {name: "Inspect", exact: true}).click();
  await expect(page.getByRole("dialog", {name: "Blocked request"})).toContainText("unsigned");
  await page.keyboard.press("Escape");
  await page.goto("/deliveries");
  await page.getByRole("button", {name: "Inspect", exact: true}).click();
  await expect(page.getByRole("dialog", {name: "Event delivery"})).toContainText("Receipt confirms");
  await page.keyboard.press("Escape");
  await page.getByRole("button", {name: "Receive event copies", exact: true}).click();
  await expect(page.getByRole("button", {name: "Stop receiving copies", exact: true})).toBeVisible();
  await page.getByRole("button", {name: "Stop receiving copies", exact: true}).click();
  await expect(page.getByRole("button", {name: "Receive event copies", exact: true})).toBeVisible();
  await page.goto("/live");
  await page.getByRole("button", {name: "Connect", exact: true}).click();
  await expect(page.getByRole("button", {name: "Inspect", exact: true})).toBeVisible();
  await page.getByRole("button", {name: "Disconnect", exact: true}).click();
  await page.goto("/access");
  await page.getByRole("textbox", {name: "Carbon or Silicon ID", exact: true}).fill(runAccounts().friend.id);
  await page.getByRole("button", {name: "Grant access", exact: true}).click();
  await expect(page.locator(".hook-account").filter({hasText: runAccounts().friend.id})).toBeVisible();
  await page.getByRole("textbox", {name: "Allow Carbon or Silicon", exact: true}).fill(runAccounts().friend.id);
  await page.getByRole("button", {name: "Allow account", exact: true}).click();
  await expect(page.getByRole("button", {name: "Remove", exact: true})).toBeVisible();
  const friend = await accountsSession(browser, "friend");
  const friendPage = await friend.newPage(); await signIn(friendPage, runAccounts().friend.email);
  await expect(friendPage.locator(".hook-card").filter({hasText: "Release events"})).toBeVisible();
  await expect(friendPage.getByRole("button", {name: "New hook", exact: true})).toHaveCount(0);
  const denied = await friend.request.post(`${BASE}/api/api/v3/silicons/${silicon.uuid}/hooks`, {headers: sameOrigin({"Idempotency-Key": randomUUID()}), data: {name: "Denied"}});
  expect(denied.status()).toBe(403);
  await friend.close();
  await page.goto("/hooks");
  await card.getByRole("button", {name: "Edit", exact: true}).click();
  await page.getByRole("textbox", {name: "Description", exact: true}).fill("Edited through the browser");
  await page.getByRole("button", {name: "Save changes", exact: true}).click();
  await expect(card).toContainText("Edited through the browser");
  await card.getByRole("button", {name: "Disable", exact: true}).click();
  await expect(card).toContainText("disabled");
  await card.getByRole("button", {name: "Enable", exact: true}).click();
  await expect(card).toContainText("active");
  await page.getByRole("checkbox", {name: "Select visible hooks", exact: true}).click();
  await page.getByRole("button", {name: "Disable selected", exact: true}).click();
  await expect(card).toContainText("disabled");
  await page.getByRole("checkbox", {name: "Select visible hooks", exact: true}).click();
  await page.getByRole("button", {name: "Enable selected", exact: true}).click();
  await expect(card).toContainText("active");
  await card.getByRole("button", {name: "View details", exact: true}).click();
  await page.getByRole("button", {name: "Rotate signing secret", exact: true}).click();
  await page.getByRole("button", {name: "Rotate", exact: true}).click();
  await expect(reveal).toBeVisible();
  const rotatedSecret = (await reveal.locator("code").allTextContents())[1]!;
  expect(rotatedSecret).not.toBe(secret);
  await reveal.getByRole("button", {name: "Done", exact: true}).click();
  await card.getByRole("button", {name: "View details", exact: true}).click();
  await page.getByRole("button", {name: "Rotate endpoint URL", exact: true}).click();
  await page.getByRole("button", {name: "Rotate URL", exact: true}).click();
  const endpointReveal = page.getByRole("dialog", {name: "Endpoint ready"});
  await expect(endpointReveal).toBeVisible();
  expect(await endpointReveal.locator("code").textContent()).not.toBe(endpoint);
  await endpointReveal.getByRole("button", {name: "Done", exact: true}).click();
  await card.getByRole("button", {name: "View details", exact: true}).click();
  await page.getByRole("button", {name: "Delete hook", exact: true}).click();
  await page.getByRole("button", {name: "Delete", exact: true}).click();
  await expect(card).toContainText("deleted");
  await card.getByRole("button", {name: "Restore", exact: true}).click();
  await expect(card).toContainText("active");
  await page.getByRole("button", {name: "Connect Accounts", exact: true}).click();
  const accountsReveal = page.getByRole("dialog", {name: "Endpoint ready"});
  await expect(accountsReveal).toBeVisible();
  await expect(accountsReveal).toContainText("webhook");
  await accountsReveal.getByRole("button", {name: "Done", exact: true}).click();
  mkdirSync("screens", {recursive: true});
  for (const theme of ["light", "dark"] as const) {
    await page.emulateMedia({colorScheme: theme, reducedMotion: "reduce"});
    for (const width of [1440, 390]) {
      await page.setViewportSize({width, height: width === 390 ? 844 : 960});
      for (const path of ["hooks", "history", "blocked", "deliveries", "live", "access", "settings"]) {
        await page.goto(`/${path}`); await expect(page.getByRole("heading", {level: 1})).toBeVisible();
        await page.waitForTimeout(250);
        expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), `${path} overflows at ${width}`).toBe(true);
        await page.screenshot({path: `screens/${path}-${theme}-${width}.png`, fullPage: true});
      }
    }
  }
  expect(errors).toEqual([]);
  await context.close();
});
