// Generated by ../build.py; credentials are supplied by the runtime.
const SPEC={
  "slug": "requests",
  "name": "Hook Requests",
  "subtitle": "Application traffic, response codes and route latency",
  "queries": {
    "totals": "SELECT toInt32(count()) AS requests,toInt32(countIf(status>=400 AND status<500)) AS client_errors,toInt32(countIf(status>=500)) AS server_errors,quantileExact(0.95)(latency_ms) AS p95_ms FROM (SELECT record.event.event_id::String AS event_id, any(record.recorded_at_ms::Float64) AS at_ms, any(record.event.source::String) AS source, any(record.event.step::String) AS event, any(record.event.outcome::String) AS outcome, any(record.event.operation::String) AS operation, any(record.event.route::String) AS route, any(record.event.method::String) AS method, any(record.event.status::Nullable(Int32)) AS status, any(record.event.duration_ms::Nullable(Float64)) AS latency_ms, any(record.event.progress::Nullable(Int32)) AS progress, any(record.event.version::String) AS version, any(record.event.trace_id::String) AS request_id, greatest(0., toFloat64(min(registered_ts_ms)) - at_ms) AS lag_ms FROM siliconhook WHERE record.service::String = 'silicon-hook' AND record.environment_id::String = '00000000-0000-0000-0000-000000000000' AND record.recorded_at_ms::Float64 >= toUnixTimestamp64Milli(now64()) - 86400000 AND record.event.event_id::String != '' AND record.event.step::String != 'verification' GROUP BY event_id) WHERE source = 'backend' AND event = 'request' AND status >= 100 AND route NOT IN ('/healthz','/readyz','/api/version','/api/v1/version')",
    "routes": "SELECT method,route,toInt32(count()) AS requests,toInt32(countIf(status>=400 AND status<500)) AS client_errors,toInt32(countIf(status>=500)) AS server_errors,avg(latency_ms) AS avg_ms,quantileExact(0.95)(latency_ms) AS p95_ms FROM (SELECT record.event.event_id::String AS event_id, any(record.recorded_at_ms::Float64) AS at_ms, any(record.event.source::String) AS source, any(record.event.step::String) AS event, any(record.event.outcome::String) AS outcome, any(record.event.operation::String) AS operation, any(record.event.route::String) AS route, any(record.event.method::String) AS method, any(record.event.status::Nullable(Int32)) AS status, any(record.event.duration_ms::Nullable(Float64)) AS latency_ms, any(record.event.progress::Nullable(Int32)) AS progress, any(record.event.version::String) AS version, any(record.event.trace_id::String) AS request_id, greatest(0., toFloat64(min(registered_ts_ms)) - at_ms) AS lag_ms FROM siliconhook WHERE record.service::String = 'silicon-hook' AND record.environment_id::String = '00000000-0000-0000-0000-000000000000' AND record.recorded_at_ms::Float64 >= toUnixTimestamp64Milli(now64()) - 86400000 AND record.event.event_id::String != '' AND record.event.step::String != 'verification' GROUP BY event_id) WHERE source = 'backend' AND event = 'request' AND status >= 100 AND route NOT IN ('/healthz','/readyz','/api/version','/api/v1/version') GROUP BY method,route ORDER BY requests DESC LIMIT 45",
    "recent": "SELECT at_ms,method,route,status,latency_ms,request_id FROM (SELECT record.event.event_id::String AS event_id, any(record.recorded_at_ms::Float64) AS at_ms, any(record.event.source::String) AS source, any(record.event.step::String) AS event, any(record.event.outcome::String) AS outcome, any(record.event.operation::String) AS operation, any(record.event.route::String) AS route, any(record.event.method::String) AS method, any(record.event.status::Nullable(Int32)) AS status, any(record.event.duration_ms::Nullable(Float64)) AS latency_ms, any(record.event.progress::Nullable(Int32)) AS progress, any(record.event.version::String) AS version, any(record.event.trace_id::String) AS request_id, greatest(0., toFloat64(min(registered_ts_ms)) - at_ms) AS lag_ms FROM siliconhook WHERE record.service::String = 'silicon-hook' AND record.environment_id::String = '00000000-0000-0000-0000-000000000000' AND record.recorded_at_ms::Float64 >= toUnixTimestamp64Milli(now64()) - 86400000 AND record.event.event_id::String != '' AND record.event.step::String != 'verification' GROUP BY event_id) WHERE source = 'backend' AND event = 'request' AND status >= 100 AND route NOT IN ('/healthz','/readyz','/api/version','/api/v1/version') ORDER BY at_ms DESC LIMIT 40"
  },
  "cards": [
    {
      "label": "App requests",
      "key": "requests",
      "detail": "Health, readiness and version probes excluded",
      "tone": "neutral",
      "unit": "",
      "group": "totals"
    },
    {
      "label": "Client errors \u00b7 4xx",
      "key": "client_errors",
      "detail": "Includes expected authorization refusals",
      "tone": "warn",
      "unit": "",
      "group": "totals"
    },
    {
      "label": "Server errors \u00b7 5xx",
      "key": "server_errors",
      "detail": "Completed backend request failures",
      "tone": "danger",
      "unit": "",
      "group": "totals"
    },
    {
      "label": "P95 latency",
      "key": "p95_ms",
      "detail": "Across all included requests",
      "tone": "neutral",
      "unit": "ms",
      "group": "totals"
    }
  ],
  "tables": [
    {
      "rows_key": "routes",
      "id": "routes",
      "title": "Route performance",
      "note": "Top 45 routes. Nullable latency remains unknown when absent.",
      "columns": [
        {
          "key": "method",
          "label": "Method",
          "kind": "text"
        },
        {
          "key": "route",
          "label": "Route",
          "kind": "text"
        },
        {
          "key": "requests",
          "label": "Requests",
          "kind": "number"
        },
        {
          "key": "client_errors",
          "label": "4xx",
          "kind": "number"
        },
        {
          "key": "server_errors",
          "label": "5xx",
          "kind": "number"
        },
        {
          "key": "avg_ms",
          "label": "Average",
          "kind": "ms"
        },
        {
          "key": "p95_ms",
          "label": "P95",
          "kind": "ms"
        }
      ]
    },
    {
      "rows_key": "recent",
      "id": "recent",
      "title": "Recent requests",
      "note": "Latest 40 completed requests. Route templates contain no private URL values.",
      "columns": [
        {
          "key": "at_ms",
          "label": "Recorded",
          "kind": "time"
        },
        {
          "key": "method",
          "label": "Method",
          "kind": "text"
        },
        {
          "key": "route",
          "label": "Route",
          "kind": "text"
        },
        {
          "key": "status",
          "label": "Status",
          "kind": "status"
        },
        {
          "key": "latency_ms",
          "label": "Latency",
          "kind": "ms"
        },
        {
          "key": "request_id",
          "label": "Trace ID",
          "kind": "trace"
        }
      ]
    }
  ]
};
const TRACE_SQL="SELECT at_ms,source,event,outcome,operation,route,status,latency_ms,request_id FROM (SELECT record.event.event_id::String AS event_id, any(record.recorded_at_ms::Float64) AS at_ms, any(record.event.source::String) AS source, any(record.event.step::String) AS event, any(record.event.outcome::String) AS outcome, any(record.event.operation::String) AS operation, any(record.event.route::String) AS route, any(record.event.method::String) AS method, any(record.event.status::Nullable(Int32)) AS status, any(record.event.duration_ms::Nullable(Float64)) AS latency_ms, any(record.event.progress::Nullable(Int32)) AS progress, any(record.event.version::String) AS version, any(record.event.trace_id::String) AS request_id, greatest(0., toFloat64(min(registered_ts_ms)) - at_ms) AS lag_ms FROM siliconhook WHERE record.service::String = 'silicon-hook' AND record.environment_id::String = '00000000-0000-0000-0000-000000000000' AND record.recorded_at_ms::Float64 >= toUnixTimestamp64Milli(now64()) - 86400000 AND record.event.event_id::String != '' AND record.event.step::String != 'verification' GROUP BY event_id)";

function present(raw){
 const data={title:SPEC.name,subtitle:SPEC.subtitle,scope:'Production · last 24 hours · deduplicated event IDs · verification probes excluded',generated_at:new Date().toISOString(),trace_enabled:true,raw,tables:SPEC.tables,cards:SPEC.cards.map(c=>({...c,value:raw[c.group]?.[0]?.[c.key]??null}))};
 if(SPEC.slug==='overview'){
  data.services=['backend','worker','web','daemon'].map(source=>({source,...(raw.sources?.find(r=>r.source===source)||{last_seen_ms:null})}));
  const start=Math.floor((Date.now()-86400000)/3600000)*3600000;
  const byHour=new Map((raw.trend||[]).map(r=>[Number(r.at_ms),Number(r.value)]));
  data.chart={title:'Event volume',note:'Hourly buckets · UTC · first and current hours are partial',points:Array.from({length:25},(_,i)=>({at_ms:start+i*3600000,value:byHour.get(start+i*3600000)||0}))};
 }
 const bytes=v=>{let n=0;for(const c of JSON.stringify(v)){const p=c.codePointAt(0);n+=p<128?1:p<2048?2:p<65536?3:4;}return n;};
 while(bytes(data)>60000){const largest=Object.values(raw).filter(r=>Array.isArray(r)&&r.length>5).sort((a,b)=>JSON.stringify(b).length-JSON.stringify(a).length)[0];if(!largest)throw new Error('Window state exceeds limit');largest.pop();data.rows_trimmed=true;}
 return data;
}
export default defineProcessor({
 init:async()=>{const raw={};for(const [key,sql] of Object.entries(SPEC.queries))raw[key]=await mission_control.query(sql);return present(raw);},
 subscriptions:Object.fromEntries(Object.entries(SPEC.queries).map(([key,sql])=>[key,{triggers:[{table:'siliconhook'}],sql,mode:'snapshot',onTrigger:(json,rows)=>present({...json.raw,[key]:rows})}])),
 tools:{summary:{args:{},run:json=>({title:json.title,scope:json.scope,generated_at:json.generated_at,cards:json.cards})},trace_request:{args:{request_id:'string'},run:async(json,{request_id})=>{if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(request_id))throw new Error('Enter a valid trace UUID');return {request_id,rows:await mission_control.query(TRACE_SQL+" WHERE request_id='"+request_id.toLowerCase()+"' ORDER BY at_ms ASC LIMIT 40")};}}}
});
